#!/usr/bin/env python3
"""
Utility script to analyze the planning_log.csv file generated by the High Level Planner.
"""

import pandas as pd
import sys
from pathlib import Path


def analyze_csv(csv_path):
    """
    Analyze and display statistics from the planning log CSV.
    
    Args:
        csv_path: Path to the planning_log.csv file
    """
    if not Path(csv_path).exists():
        print(f"Error: CSV file not found at {csv_path}")
        return
    
    # Read CSV
    df = pd.read_csv(csv_path)
    
    print("=" * 80)
    print("PLANNING LOG ANALYSIS")
    print("=" * 80)
    print(f"\nCSV File: {csv_path}")
    print(f"Total Problems Processed: {len(df)}")
    
    # Success/Failure Statistics
    print("\n" + "=" * 80)
    print("SUCCESS RATE")
    print("=" * 80)
    
    success_count = df['is_valid'].sum()
    failed_count = len(df) - success_count
    success_rate = (success_count / len(df)) * 100 if len(df) > 0 else 0
    
    print(f"Successful Plans: {success_count}/{len(df)} ({success_rate:.1f}%)")
    print(f"Failed Plans: {failed_count}/{len(df)} ({100-success_rate:.1f}%)")
    
    # Loop Statistics
    print("\n" + "=" * 80)
    print("ITERATION STATISTICS")
    print("=" * 80)
    
    print(f"Average Loops (All): {df['num_loops'].mean():.2f}")
    print(f"Average Loops (Successful): {df[df['is_valid'] == True]['num_loops'].mean():.2f}")
    print(f"Max Loops: {df['num_loops'].max()}")
    print(f"Min Loops: {df['num_loops'].min()}")
    
    # Loop distribution
    print("\nLoop Distribution:")
    loop_dist = df['num_loops'].value_counts().sort_index()
    for loops, count in loop_dist.items():
        print(f"  {loops} loop(s): {count} problem(s)")
    
    # Status breakdown
    print("\n" + "=" * 80)
    print("STATUS BREAKDOWN")
    print("=" * 80)
    
    status_counts = df['status'].value_counts()
    for status, count in status_counts.items():
        print(f"{status.capitalize()}: {count}")
    
    # Domain/Constraint info (if available)
    if 'domain_name' in df.columns:
        print("\n" + "=" * 80)
        print("DOMAIN INFORMATION")
        print("=" * 80)
        print(f"Domain: {df['domain_name'].iloc[0]}")
        print(f"Constraints: {df['num_constraints'].iloc[0]}")
    
    # Problem-by-problem results
    print("\n" + "=" * 80)
    print("DETAILED RESULTS")
    print("=" * 80)
    
    for _, row in df.iterrows():
        status_symbol = "✓" if row['is_valid'] else "✗"
        print(f"{status_symbol} Problem {row['problem_id']}: {row['status'].upper()} "
              f"(Loops: {row['num_loops']}, Valid: {row['is_valid']})")
    
    # Export summary option
    print("\n" + "=" * 80)
    print("EXPORT OPTIONS")
    print("=" * 80)
    print("\nTo export specific columns, you can use:")
    print("  df = pd.read_csv('planning_log.csv')")
    print("  df[['problem_id', 'status', 'num_loops', 'is_valid']].to_csv('summary.csv')")


def export_summary(csv_path, output_path=None):
    """
    Export a simplified summary CSV with key metrics only.
    
    Args:
        csv_path: Path to the planning_log.csv file
        output_path: Path for the output summary CSV (default: same dir as input)
    """
    df = pd.read_csv(csv_path)
    
    # Create summary with essential columns
    summary_cols = ['timestamp', 'problem_id', 'domain_name', 'num_constraints', 
                   'is_valid', 'num_loops', 'status']
    
    # Add optional columns if they exist
    optional_cols = ['ltl_formula']
    for col in optional_cols:
        if col in df.columns:
            summary_cols.append(col)
    
    summary_df = df[summary_cols]
    
    if output_path is None:
        csv_dir = Path(csv_path).parent
        output_path = csv_dir / 'planning_summary.csv'
    
    summary_df.to_csv(output_path, index=False)
    print(f"Summary exported to: {output_path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python analyze_csv.py <path_to_planning_log.csv> [--export]")
        print("\nExample:")
        print("  python analyze_csv.py data/blocksworld/data/data_2/results/planning_log.csv")
        print("  python analyze_csv.py data/blocksworld/data/data_2/results/planning_log.csv --export")
        sys.exit(1)
    
    csv_path = sys.argv[1]
    
    # Check if export flag is provided
    if len(sys.argv) > 2 and sys.argv[2] == '--export':
        export_summary(csv_path)
        print("\nSummary analysis:")
    
    analyze_csv(csv_path)
