import { useMemo, useState } from 'react'
import type { A2UIAction, A2UIBlueprint, A2UIObject } from '@/types'

interface A2UIRendererProps {
  blueprint: A2UIBlueprint
  onApplyPredicate: (predicate: string) => void
}

function resolvePredicate(template: string, target: string, destination?: string): string {
  return template
    .split('{target}').join(target)
    .split('{destination}').join(destination || target)
}

function ActionButton({
  action,
  target,
  onApply,
}: {
  action: A2UIAction
  target: string
  onApply: (predicate: string) => void
}) {
  if (action.type !== 'click') return null

  return (
    <button
      type="button"
      className="px-2 py-1 text-[11px] rounded bg-lapis-accent/20 border border-lapis-accent/40 text-lapis-accent"
      onClick={() => onApply(resolvePredicate(action.update_predicate, target, target))}
    >
      Apply
    </button>
  )
}

function ObjectChip({ obj }: { obj: A2UIObject }) {
  return (
    <div className="rounded-md border border-lapis-border bg-lapis-bg px-3 py-2 text-xs text-lapis-text">
      {obj.label}
    </div>
  )
}

export default function A2UIRenderer({ blueprint, onApplyPredicate }: A2UIRendererProps) {
  const [draggingId, setDraggingId] = useState<string | null>(null)

  const clickActionsByTarget = useMemo(() => {
    const map = new Map<string, A2UIAction[]>()
    for (const action of blueprint.actions) {
      if (action.type !== 'click') continue
      const key = action.target_id
      const previous = map.get(key) || []
      map.set(key, [...previous, action])
    }
    return map
  }, [blueprint.actions])

  const dragActions = blueprint.actions.filter((action) => action.type === 'drag')

  const onDropTarget = (destination: string) => {
    if (!draggingId) return
    const action = dragActions.find((candidate) => candidate.target_id === '*' || candidate.target_id === draggingId)
    if (!action) return
    onApplyPredicate(resolvePredicate(action.update_predicate, draggingId, destination))
    setDraggingId(null)
  }

  return (
    <div className="rounded-xl border border-lapis-border bg-lapis-card p-4 space-y-3">
      <div>
        <p className="text-sm font-semibold text-lapis-text">A2UI Renderer</p>
        <p className="text-xs text-lapis-text-secondary">Dynamic UI generated by the agent blueprint.</p>
      </div>

      {blueprint.layout === 'grid' && (
        <div className="grid grid-cols-2 gap-2">
          {blueprint.objects.map((obj) => (
            <div
              key={obj.id}
              className="rounded-lg border border-lapis-border bg-lapis-bg/60 p-2 space-y-2"
              onDragOver={(event) => event.preventDefault()}
              onDrop={() => onDropTarget(obj.id)}
            >
              <div className="flex items-center justify-between gap-2">
                <div
                  draggable={obj.draggable}
                  onDragStart={() => setDraggingId(obj.id)}
                  className={obj.draggable ? 'cursor-grab active:cursor-grabbing' : ''}
                >
                  <ObjectChip obj={obj} />
                </div>
                {(clickActionsByTarget.get(obj.id) || clickActionsByTarget.get('*') || []).map((action, idx) => (
                  <ActionButton
                    key={`${obj.id}-${idx}`}
                    action={action}
                    target={obj.id}
                    onApply={onApplyPredicate}
                  />
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {blueprint.layout === 'canvas' && (
        <div className="grid grid-cols-2 gap-2">
          {blueprint.objects.map((obj) => (
            <div
              key={obj.id}
              className="rounded-lg border border-lapis-border bg-lapis-bg/60 p-3"
              onDragOver={(event) => event.preventDefault()}
              onDrop={() => onDropTarget(obj.id)}
            >
              <div
                draggable={obj.draggable}
                onDragStart={() => setDraggingId(obj.id)}
                className={obj.draggable ? 'cursor-grab active:cursor-grabbing' : ''}
              >
                <ObjectChip obj={obj} />
              </div>
            </div>
          ))}
        </div>
      )}

      {blueprint.layout === 'form' && (
        <div className="space-y-2">
          {blueprint.objects.map((obj) => (
            <div key={obj.id} className="rounded border border-lapis-border bg-lapis-bg px-3 py-2 text-xs text-lapis-text">
              {obj.label}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
